# -*- coding: utf-8 -*-
"""MyPublisher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PtGe257GmZaaKx_5HVgpsZFYSFtDLbin
"""

pip install google-cloud-pubsub

import csv
import time
from google.cloud import pubsub_v1
import os
project = 'My First Project'
pubsub_topic = 'projects/vivid-now-271806/topics/movies'
service_account_key = '/content/vivid-now-271806-e22933a07e8a.json'
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]= service_account_key
input_file = '/content/movies.csv'
publisher = pubsub_v1.PublisherClient()
with open('movies.csv', 'rb') as file:
    for row in file:
        print('Publishing in Topic')
        publisher.publish(pubsub_topic,row)
        time.sleep(1)