# -*- coding: utf-8 -*-
"""Session_Window_Processor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OZDkq18azTVcM2FjrDaXHgkp1CP54OHP
"""

pip install apache_beam

pip install google-cloud-pubsub

import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions,StandardOptions
import os
from apache_beam import window
from apache_beam.transforms.combiners import Count
import time


serviceAccount = '/content/vivid-now-271806-e22933a07e8a.json'
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]= serviceAccount

input_subscription = 'projects/vivid-now-271806/subscriptions/ratings_subscription'

options= PipelineOptions()
options.view_as(StandardOptions).streaming= True

p = beam.Pipeline(options=options)

rating_count = 'projects/vivid-now-271806/topics/rating_count_window'

def format(element):
        (genre,movies_count)=element
        return "{m} movies in genre {g}".format(g = genre, m=movies_count).encode('utf-8') 

pubsub_pipeline = (
    p
    | 'Read from pubsub topic' >> beam.io.ReadFromPubSub(subscription= input_subscription)
    | 'Split the records by comma' >> beam.Map(lambda row: row.decode('utf-8').split(','))
    | 'Form Key Value Pair' >> beam.Map(lambda row: (row[2],row[0]))
    | 'Create Session Window' >> beam.WindowInto(window.Sessions(25))
    | 'Count the ratings' >> Count.PerKey()
    | 'Format' >> beam.Map(format)
    | 'Publish to output topic' >> beam.io.WriteStringsToPubSub(rating_count)
)
result = p.run()
result.wait_until_finish()