# -*- coding: utf-8 -*-
"""Session_Publisher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X-SLulDCyxIVzxdafClVaKKxDtllkENw
"""

pip install google-cloud-pubsub

import csv
import time
from google.cloud import pubsub_v1
import os
project = 'My First Project'
pubsub_topic = 'projects/vivid-now-271806/topics/ratings'
service_account_key = '/content/vivid-now-271806-e22933a07e8a.json'
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]= service_account_key
input_file = '/content/movies.csv'
publisher = pubsub_v1.PublisherClient()
with open('movies.csv', 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    next(csvreader)
    for row in csvreader:
        print('Publishing in Topic ' + ','.join(row))
        publisher.publish(pubsub_topic,','.join(row).encode('utf-8'))
        time.sleep(1)