# -*- coding: utf-8 -*-
"""Lecture9_Tongue_Twister.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eb2m50PmIC1FdgA_RC2qwOntdjAsFS5B
"""

import apache_beam as beam

words=['peter','piper','pickled','picked','peck','pepper']

def SplitRow(element):
  return element.split(' ')


def FindWord(element):
 if element in words:
    return True

class SplitRow(beam.DoFn):
  def process(self,element):
    return element.split(' ')


class CalculateFrequency(beam.DoFn):
  def process(self,element):
    (key,value) = element
    return [(key,sum(value))]

   

p1 = beam.Pipeline()

freq = (
    p1
    |'Read your input file' >> beam.io.ReadFromText('Peter_Piper.txt')
    |'Split Records with Space' >> beam.ParDo(SplitRow())
    |'Filtering records' >> beam.Filter(FindWord)
    |'Create tupled records'>> beam.Map(lambda record: (record,1))
    |'Group By Key'>> beam.GroupByKey()
    |'Calculate Frequency of words' >> beam.ParDo(CalculateFrequency())
    |beam.io.WriteToText('result')
)
p1.run()

!cat result-00000-of-00001