# -*- coding: utf-8 -*-
"""Lecture10_Pardo_Customers_Newyork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yLEe40qi1xXedqVBcKYt92m6L4cPauFi
"""

import apache_beam as beam
p1 = beam.Pipeline()

class SplitRow(beam.DoFn):
  def process(self,element):
    return [element.split(',')]

class FilterCustomer(beam.DoFn):
  def process(self,element):
    if element[2]=='NY' and int(element[3])>20:
      return [element]


customers = (
    p1
    |beam.io.ReadFromText('Customers_age.txt')
    |beam.ParDo(SplitRow())
    |beam.ParDo(FilterCustomer())
    |beam.io.WriteToText('result')
)
p1.run()

!cat result-00000-of-00001