# -*- coding: utf-8 -*-
"""Lecture12_Flatten.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZSp_mz8UC7fmSqKSL8qGAp7-QlfKFXLy
"""

! pip install apache_beam

import apache_beam as beam

p = beam.Pipeline()

even = {2,4,6,8}
odd = {1,3,5,7,9}
name = ('John','Jim','Mary')

even_pc = p | 'Create Pcollection from Even number' >> beam.Create(even)
odd_pc = p | 'Create Pcollection from Odd Number' >> beam.Create(odd)
name_pc = p | 'Create Pcollection from Name' >> beam.Create(name)

result = ((even_pc,odd_pc,name_pc) | beam.Flatten()) | beam.Map(print)
p.run()