# -*- coding: utf-8 -*-
"""Lecture13_partition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16B6kL6es112LUzOw1sa7dJBDz_ndc8I2
"""

import apache_beam as beam

p = beam.Pipeline()
number = {1,2,3,4,5,6,7,8}

def partition_fn(element,num_partition):
  return 0 if element%2 ==0 else 1


number_pc = p| beam.Create(number)| beam.Partition(partition_fn,2)

number_pc[1]| 'Printing first partition' >> beam.Map(print)

p.run()