# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11MlXD9FBJCiqIFtUK15XQuE_RGdjG4IL
"""

pip install apache_beam

import apache_beam as beam
p1 = beam.Pipeline()

side_list = list()
with open ('customers_exclude.txt','r') as exclude_file:
  for cust_id in exclude_file:
    side_list.append(cust_id.rstrip())

print(side_list)

class SplitRow(beam.DoFn):
  def process(self,element,side_list):
    customer = element.split(',')
    if customer[0] not in side_list:
      return [customer]

customers = (
    p1
    |beam.io.ReadFromText('Customers_age.txt')
    |beam.ParDo(SplitRow(),side_list)
    |beam.io.WriteToText('result')
)
p1.run()

!cat result-00000-of-00001