# -*- coding: utf-8 -*-
"""Tumbling_Subscriber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJxz5AUwunwUDXWiwaNmJMQ1ZjF5HUeH
"""

pip install google-cloud-pubsub

from google.cloud import pubsub_v1
import time
import os

serviceAccount = '/content/vivid-now-271806-e22933a07e8a.json'
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]= serviceAccount

subscription_path = 'projects/vivid-now-271806/subscriptions/rating_count_subscription'
subscriber = pubsub_v1.SubscriberClient()

def callback(message):
  print(('Recieved Message: {}'.format(message)))
  message.ack()

subscriber.subscribe(subscription_path,callback=callback)

while True:
  time.sleep(1)