# -*- coding: utf-8 -*-
"""11_CogroupByKeyipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y7G2j-hPhBaF9AGPp776cvs9KI23eWeF
"""

import apache_beam as beam

p = beam.Pipeline() 
movie_name = [
    (1, 'SpiderMan'),
    (2, 'Avenger'),
    (3, 'Titanic'),
    (4, 'Green Miles'),
]
movies_rating = [
    (1, 3.5),
    (2, 4),
    (1,4.5),
    (3,3.5),
    (2,4.5)
]

name = p | 'Create Name Pcollection' >> beam.Create(movie_name)
ratings = p | 'Create Rating Pcollection' >> beam.Create(movies_rating)

joinedResult= ({'movie_name':name,'movie_rating':ratings} | beam.CoGroupByKey()) | beam.Map(print)

p.run()