# -*- coding: utf-8 -*-
"""Lecture9_Tongue_Twister.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eb2m50PmIC1FdgA_RC2qwOntdjAsFS5B
"""

!pip install apache_beam

import apache_beam as beam

words=['peter','piper','pickled','picked','peck','pepper']
def FindWord(element):
 if element in words:
    return True

p1 = beam.Pipeline()

freq = (
    p1
    |beam.io.ReadFromText('Peter_Piper.txt')
    |beam.FlatMap(lambda record: record.split(' '))
    |beam.Filter(FindWord)
    |beam.Map(lambda record: (record,1))
    |beam.CombinePerKey(sum)
    |beam.io.WriteToText('result')
)
p1.run()

!cat result-00000-of-00001